language: node_js
node_js:
  - "0.10"
before_script:
  - curl https://install.meteor.com | /bin/sh
  - npm install
  - npm install -g meteorite
  - chromedriver --port=9515:
      background: true
script:
  - ./test.js
